# The value of the damage-multiplier setting is multiplied by the base damage dealt by the player to calculate the final damage dealt.
# For example, if the base damage dealt by a player is 10, and the damage-multiplier setting is 1.33, then the final damage dealt would be 10 * 1.33 = 13.3.

# The value of this setting determines how much extra damage players will deal
# when using eligible weapons.
damage-multiplier: 1.33

# The values in this list specify the types of weapons that are eligible for
# the damage boost.
eligible-materials:
  - DIAMOND_SWORD
  - DIAMOND_AXE